### PR TITLE
Update JMS guide to JmsListener

### PR DESCRIPTION
**Pull request by snicoll**
Update the messaging with JMS guide to use the new JmsListener annotation
introduced in Spring Framework 4.1

### CODE REVIEW

**Comment by snicoll** [comment]
Hold on, I forgot some documentation link. I'll push an update in a min.

**Comment by gregturn** [comment]
I think that if a given bean is unneeded, I'd go ahead and remove it. We can add a NOTE with a link indicating the option to override.

**Comment by snicoll** [comment]
I'd rather keep it as it makes the link between the factory and the listener. It's a bit too magic at first without that. If you remove it then you have to spend too much time basically explaining how a container shows up.

**Comment by snicoll** [comment]
Fixed the typo, thanks!

**Pull request merged**
